# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb072ad391a0992708dd976e048ae86b"
name = "commission-fee-amex"
handle = "commission-fee-amex"
application_url = "https://tap-internship-males-ot.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,read_checkouts,read_discounts,read_orders,read_payment_customizations,write_cart_transforms,write_checkouts,write_discounts,write_orders,write_payment_customizations,write_products,read_customers"

[auth]
redirect_urls = [
  "https://tap-internship-males-ot.trycloudflare.com/auth/callback",
  "https://tap-internship-males-ot.trycloudflare.com/auth/shopify/callback",
  "https://tap-internship-males-ot.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
