api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "cart-transformer-fee"

uid = "14a73b33-360d-97ca-c171-ab39ccbb45c78ed59109"

type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
